// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbAGoER1riXEKWdrj0IovjwaIyFdWfTyI',
    appId: '1:825508909314:web:165f8439ba1c1928aa321b',
    messagingSenderId: '825508909314',
    projectId: 'easy-rpg-85361',
    authDomain: 'easy-rpg-85361.firebaseapp.com',
    databaseURL: 'https://easy-rpg-85361-default-rtdb.firebaseio.com',
    storageBucket: 'easy-rpg-85361.appspot.com',
    measurementId: 'G-996WPN3L9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx7bBRTCwjfwtnGLhuQUgvybvpk5hiJXM',
    appId: '1:825508909314:android:be8e7f3d4f979896aa321b',
    messagingSenderId: '825508909314',
    projectId: 'easy-rpg-85361',
    databaseURL: 'https://easy-rpg-85361-default-rtdb.firebaseio.com',
    storageBucket: 'easy-rpg-85361.appspot.com',
  );
}
